#!/usr/bin/env zsh
# Import plate model into Corelle (running in a docker container)
# Limitations: no plate polygons yet, so all features must be explicitly
# tied to a plate ID.
corelle=${CORELLE_DIR:-"../../corelle"}
container_id=$(cd $corelle && docker-compose ps -q api)
echo "$container_id"

ex() {
  # Run in container
  docker exec $container_id $@
}

pth=/tmp/Wilson_etal2005
docker cp output $container_id:"$pth"
echo "Running import process"
ex corelle import "Wilson2005" \
  --min-age 0 \
  --max-age 37 \
  --overwrite \
  "$pth/plate-polygons.geojson" \
  "$pth/Wilson_etal2005.rot"
ex rm -rf "$pth"
